const sidebars = {
  javascript: [{ type: 'autogenerated', dirName: 'js-basic' }],
  practiceInput: [{ type: 'autogenerated', dirName: 'practice-input' }],
  npm: [{ type: 'autogenerated', dirName: 'npm' }],
  publishTutorialSurge: [{ type: 'autogenerated', dirName: 'publish-tutorial-surge' }]
}

module.exports = sidebars
