const sidebars = {
  javascript: [{ type: 'autogenerated', dirName: 'js-basic' }],
  practiceInput: [{ type: 'autogenerated', dirName: 'practice-input' }],
  npm: [{ type: 'autogenerated', dirName: 'npm' }],
  publishTutorial: [{ type: 'autogenerated', dirName: 'publish-tutorial' }]
}

module.exports = sidebars
